opam-version: "2.0"
synopsis: "OCaml lowering and tagged runtime observatory"
maintainer: "yardrack@users.noreply.github.com"
authors: ["yardrack"]
license: "MIT"
homepage: "https://github.com/yardrack/lamb"
bug-reports: "https://github.com/yardrack/lamb/issues"
dev-repo: "git+https://github.com/yardrack/lamb.git"
depends: [
  "ocaml" {>= "5.1"}
  "dune" {>= "3.12"}
]
build: [
  ["dune" "subst"] {dev}
  ["dune" "build" "-p" name "-j" jobs]
]
