export { analyze, freeVariables, walk } from "./analysis/index.js"
export { compile, samples, stages } from "./pipeline.js"
export { evaluate, formatValue } from "./runtime/evaluate.js"
export { decodeInteger, encodeInteger, representation, wordBits } from "./runtime/word.js"
export { LambError, tokenize } from "./syntax/lexer.js"
export { Parser, parse } from "./syntax/parser.js"
export { formatType, infer } from "./type/infer.js"
